# -*- coding: utf-8 -*-
"""matriz_espécies_um_script.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MFIiGmLCg47a6pHrmgmW4mYRojwh1F9w
"""

#SET FINAL DATAFRAME

import pandas as pd
matriz = pd.read_csv("lista_spp.csv", sep=",")
df = pd.DataFrame(matriz)

df_spp_complete = pd.DataFrame(matriz)

#SET FILES OUTPUT FILES FROM NDM/VNDM

with open("A_1_2x2_output.out") as analise_1, open("A_2_3x3_output.out") as analise_2, open("A_3_4x4_output.out")  as analise_3, open("A_4_5x5_output.out")  as analise_4:
  files = [analise_1, analise_2, analise_3, analise_4]
  for i in range(len(files)):
    n_analise = i+1
    raw_ac = files[i].readlines()

#CREATE SPECIES LISTS

    for c in range(len(raw_ac)):
      if "Consensus area" in raw_ac[c]:
        slice_1 = c
        break

    for c in range(len(raw_ac)):  
      if "INFORMATION ON ENDEMIC SPECIES" in raw_ac[c]:
        slice_2 = c
        
    del raw_ac[:slice_1]
    '''del raw_ac[slice_2 - slice_1:]'''

    ac = raw_ac

    list_n = []
    list_spp = []

    for c in range(len(ac)):
      if "Consensus area" in ac[c]:
        loc = ac[c].find("species")
        n_species = loc - 3
        n = int(ac[c][n_species:n_species+2])
        list_n.append(n)

        spp_ac = ac[c+1:c+n+1]
        list_spp.append(spp_ac)

#MATRIX AND LIST THAT WILL BECOME THE MATRIX

    import pandas as pd
    matriz = pd.read_csv("lista_spp.csv", sep=";")
    df = pd.DataFrame(matriz)

    list_list = []
    for c in range (df.shape[0]):
      list_presença = []
      for c_1 in range (len(list_spp)):
        nom_sp = df.loc[c,"Species"]
        nom_sp_bugfix = nom_sp.replace(" ","  ")
        presença = False
        for c_2 in range (len(list_spp[c_1])):
          if nom_sp in list_spp[c_1][c_2]:
            presença = True
          elif nom_sp_bugfix in list_spp[c_1][c_2]:
            presença = True
        list_presença.append(presença)
      list_list.append(list_presença)

#DATAFRAME MATRIX

    df_spp = pd.DataFrame(list_list)
    df_spp = df_spp.replace(True, 1)
    df_spp = df_spp.replace(False, 0)
    df_spp.insert(0, "Species", df["Species"])

    contador = -1
    colunas = ['Species']

    for c in range(len(ac)):
      ac_n = ac[c].count("Consensus area")
      if ac_n == 1:
        contador += 1
        nom_col = "AE_{}.{}".format(n_analise, contador)
        colunas.append(nom_col)
      ac_n = 0

    df_spp = df_spp.set_axis(colunas, axis = 1)

#CONCATENATE DATAFRAMES

    df_spp_complete = pd.merge(df_spp_complete, df_spp, on = "Species")
    df_spp_complete

df_spp_complete = df_spp_complete.transpose()
df_spp_complete.to_csv('matriz_consensos.csv', sep = ";")